POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI1ZWIyZTBkYmNiMWRlZjNkMDg4MWYyMDMiLCJpYXQiOjE1ODg3ODMxNDJ9.pBE-_Mk8GJJysJPbULWL1pNgVOBeBO-mfDBFGkyredw

{
    "title": "Full Stack Open 2020",
    "author": "Au Thori",
    "url": "www.google.fi",
    "likes": "2020"
}